### ISSUE TITLE
no such file or directory "react-auth-server\certs\server.key"

### ISSUE THREAD

**Issue by lizhoucheng** [funador/react-auth-server#1]
Hi,
When I cloned the server repo and run `npm install` and `npm start` , it gives me the error: 
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
no such file or directory, open '...\react-auth-server\certs\server.key'.

**Comment by funador** [comment]
You need to set up your certs on your own and put them in /certs.  This link should help:

[How to get HTTPS working on your local development environment in 5 minutes](https://medium.freecodecamp.org/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec)
